
name: Npm Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Build, bump & publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      # - run: npm test
      - run: npm run build

      # new release
      - name: Bump version & publish
        run: |
          git config --global user.name "Allen Lee"
          git config --global user.email "648384410li@gmail.com"

          npm version patch

          git push && git push --tags

      # to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
